/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.study;

import org.junit.Test;
import static org.junit.Assert.*;

public class HashProblemTest {
    @Test public void testSomeLibraryMethod() {
        HashProblem hashProblem = new HashProblem();
        
    }
}
